-- ============================================================
-- V1: Create all tables for SkillSwap
-- ============================================================
-- This file runs AUTOMATICALLY when Spring Boot starts (via Flyway).
-- Flyway reads all files in db/migration/ in order (V1, V2, V3...)
-- and runs each one exactly ONCE. If you need to change the schema
-- later, do NOT edit this file — create a new V3__your_change.sql.
-- ============================================================

-- ── USERS ───────────────────────────────────────────────────
-- Maps to: com.skillswap.user.User
-- One row = one registered account on the platform
CREATE TABLE users (
    id             UUID                     PRIMARY KEY,
    email          VARCHAR(255)             NOT NULL UNIQUE,
    password       VARCHAR(255)             NOT NULL,
    display_name   VARCHAR(255)             NOT NULL,
    bio            VARCHAR(1000),
    last_login     TIMESTAMP WITH TIME ZONE,
    average_rating FLOAT8                   DEFAULT 0.0,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

-- ── SKILLS ──────────────────────────────────────────────────
-- Maps to: com.skillswap.skill.Skill
-- A global catalogue of skills that users can offer or want
-- Examples: "Java" (Programming), "Guitar" (Music), "Spanish" (Language)
CREATE TABLE skills (
    id       UUID         PRIMARY KEY,
    name     VARCHAR(255) NOT NULL UNIQUE,
    category VARCHAR(255) NOT NULL
);

-- ── USER_SKILLS ──────────────────────────────────────────────
-- Maps to: com.skillswap.user.UserSkill
-- This is a JOIN TABLE between users and skills.
-- A row says: "user X OFFERS skill Y at level Z"
--          or "user X WANTS skill Y at level Z"
-- This is how the matching algorithm knows who to pair with whom.
CREATE TABLE user_skills (
    id       UUID         PRIMARY KEY,
    user_id  UUID         NOT NULL REFERENCES users(id),
    skill_id UUID         NOT NULL REFERENCES skills(id),
    type     VARCHAR(255) NOT NULL,   -- 'OFFERED' or 'WANTED'  (see SkillType enum)
    level    INTEGER      NOT NULL    -- 1 = beginner, 5 = expert
);

-- ── SESSION_REQUESTS ─────────────────────────────────────────
-- Maps to: com.skillswap.session.SessionRequest
-- Created when user A (initiator) invites user B (receiver) to swap skills.
-- The request is PENDING until B accepts or declines.
CREATE TABLE session_requests (
    id               UUID                     PRIMARY KEY,
    initiator_id     UUID                     NOT NULL REFERENCES users(id),
    receiver_id      UUID                     NOT NULL REFERENCES users(id),
    offered_skill_id UUID                     NOT NULL REFERENCES skills(id),
    wanted_skill_id  UUID                     NOT NULL REFERENCES skills(id),
    status           VARCHAR(255)             NOT NULL DEFAULT 'PENDING',  -- see RequestStatus enum
    message          VARCHAR(500),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

-- ── SESSIONS ────────────────────────────────────────────────
-- Maps to: com.skillswap.session.Session
-- Created automatically when a session_request is ACCEPTED.
-- One request → at most one session (UNIQUE on request_id).
CREATE TABLE sessions (
    id           UUID                     PRIMARY KEY,
    request_id   UUID                     NOT NULL UNIQUE REFERENCES session_requests(id),
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    mode         VARCHAR(255)             NOT NULL,  -- 'ONLINE' or 'IN_PERSON' (see SessionMode enum)
    status       VARCHAR(255)             NOT NULL DEFAULT 'SCHEDULED',  -- see SessionStatus enum
    location     VARCHAR(300)             -- only filled for IN_PERSON sessions
);

-- ── RATINGS ─────────────────────────────────────────────────
-- Maps to: com.skillswap.rating.Rating
-- After a COMPLETED session, each participant can rate the other.
-- One session can have up to 2 ratings (A rates B, B rates A).
CREATE TABLE ratings (
    id         UUID                     PRIMARY KEY,
    session_id UUID                     NOT NULL REFERENCES sessions(id),
    author_id  UUID                     NOT NULL REFERENCES users(id),  -- who wrote the rating
    target_id  UUID                     NOT NULL REFERENCES users(id),  -- who received the rating
    score      INTEGER                  NOT NULL,  -- 1 to 5
    comment    VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
